name: flutter_nfc_kit_aurora
description: "A new Flutter FFI plugin project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.2
  plugin_platform_interface: ^2.0.2
  device_platform_interface:
    git:
      url: https://gitlab.com/omprussia/flutter/demo-dart-packages.git
      ref: 
      path: device_platform_interface

BuildRequires: pkgconfig(Qt5Core)

dev_dependencies:
  ffi: ^2.0.2
  ffigen: ^9.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      aurora:
        ffiPlugin: true
        dartPluginClass: FFINFCKit
