// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/flutter_nfc_kit_aurora.h`.
///
/// Regenerate bindings with `flutter pub run ffigen --config ffigen.yaml`.
///
class FlutterNfcKitAuroraBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  FlutterNfcKitAuroraBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  FlutterNfcKitAuroraBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  late final ffi.Pointer<ffi.Int> _NfcdAdaptersModel =
      _lookup<ffi.Int>('NfcdAdaptersModel');

  int get NfcdAdaptersModel => _NfcdAdaptersModel.value;

  set NfcdAdaptersModel(int value) => _NfcdAdaptersModel.value = value;

  late final ffi.Pointer<ffi.Int> _NfcdAdaptersModelPrivate =
      _lookup<ffi.Int>('NfcdAdaptersModelPrivate');

  int get NfcdAdaptersModelPrivate => _NfcdAdaptersModelPrivate.value;

  set NfcdAdaptersModelPrivate(int value) =>
      _NfcdAdaptersModelPrivate.value = value;

  late final ffi.Pointer<ffi.Int> _QObject = _lookup<ffi.Int>('QObject');

  int get QObject => _QObject.value;

  set QObject(int value) => _QObject.value = value;

  late final ffi.Pointer<ffi.Int> _NfcdDaemonHandlerPrivate =
      _lookup<ffi.Int>('NfcdDaemonHandlerPrivate');

  int get NfcdDaemonHandlerPrivate => _NfcdDaemonHandlerPrivate.value;

  set NfcdDaemonHandlerPrivate(int value) =>
      _NfcdDaemonHandlerPrivate.value = value;
}
